[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle the landing page
[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 200

# Handle React app routes
[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ai-kitchen"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/detected"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/planner"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/history/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/payment"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/index.html"
  status = 200 